### ISSUE TITLE
error while running python try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py

### ISSUE THREAD

**Issue by great-thoughts** [benanne/kaggle-galaxies#7]
Hi, 
I was trying to run python `try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py` however, I am getting some errors. I am running this on an amazon instant with GPU 4Gb. 

```
ubuntu@ip-172-31-19-167:~/kaggle-galaxies$ python try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py
Using gpu device 0: GRID K520
Set up data loading
Preprocess validation data upfront
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/kaggle-galaxies/load_data.py", line 563, in _buffered_generation_process
    data = source_gen.next()
  File "/home/ubuntu/kaggle-galaxies/realtime_augmentation.py", line 337, in realtime_fixed_augmented_data_gen
    for k, imgs_aug in enumerate(gen):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 269, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
AttributeError: 'builtin_function_or_method' object has no attribute 'iterkeys'
Traceback (most recent call last):
  File "try_convnet_cc_multirotflip_3x69r45_maxout2048_extradense.py", line 138, in <module>
    xs_valid = [np.vstack(x_valid) for x_valid in xs_valid]
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

**Comment by great-thoughts** [comment]
I wanted to check if the data is loaded properly when I copy them to RAM via python /home/ubuntu/kaggle-galaxies/copy_data_to_shm.py. However, I find images_train_rev1 there but its empty.

**Comment by benanne** [comment]
No idea what's going on here. Maybe you're using the latest numpy version or so? This code is about 1.5 years old and has not been updated (nor will it be), so you might have to use older versions of some packages to get it to run out of the box. I recommend looking into virtualenv for that purpose.
